### ISSUE TITLE
Meta description and image tags fall back to site description and image (but it would be better if they didn't)

### ISSUE THREAD

**Issue by mazil** [takeflight/wagtail-metadata#23]
Currently the meta description tags (in their various forms) all fall back to using the site description if no specific description for that page has been added.

This seems like a good idea, but in practice it means that the description is inaccurate for most pages, and it could lead to Google penalising the page.

If there are no specific meta tags entered for the page, it would be better if they weren't output. 

This gives websites and search engines a chance to auto-generate a summary that might be closer to the real content, and might also hopefully prompt users to write better ones :)

Update: The above applies to the image tags too!

**Comment by timheap** [comment]
Is there any use for global default at all in that case? Currently the `SiteMetadataPreferences` setting has `site_image`, `site_description`, and `card_type` (for twitter). By the sounds of it, if global defaults are harmful, this setting should be removed completely.

**Comment by conatus** [comment]
Hey there! Thanks for doing this library.

Feel that for us, at least a default image would be of use. Could we add this in, turned off by a flag?

**Comment by seb-b** [comment]
Hi @conatus 

You can overwrite  `MetadataPageMixin.get_meta_image_url` to set your own fallback e.g.

```python

from wagtailmetadata.models import MetadataPageMixin

class FallbackImageMetadataMixin(MetadataPageMixin):
   def get_meta_image_url(self, request):
      if not self.search_image:
         # code here to return your fallback
         return 'https://example.com/fallback.jpeg'
      return super().get_meta_image_url(request)
   
class MyPage(FallbackImageMetadataMixin, Page):
     pass
```


You can do this like above to set a global fallback, or if needed override the method per page

**Comment by conatus** [comment]
Thanks very much @seb-b 

Presumably we could also use a site setting image field to flesh this out as well?

**Comment by seb-b** [comment]
> Thanks very much @seb-b
> 
> Presumably we could also use a site setting image field to flesh this out as well?

Yep absolutely. Site settings can be grabbed programmatically, if you're using an image field you can just overwrite `get_meta_image`

```python
from wagtailmetadata.models import MetadataPageMixin
from project.core.models import MetadataFalbackSettings

class FallbackImageMetadataMixin(MetadataPageMixin):
   def get_meta_image(self):
      if not self.search_image:
         fallback_settings = MetadataFallbackSettings.objects.get(is_default=True)
         return fallback_settings.image
      return super().get_meta_image()
```
This assumes that it's a single site setup with only one fallback settings but that should cover most cases.
