### ISSUE TITLE
Look into JSON-LD for Schema.org tags

### ISSUE THREAD

**Issue by jonnyscholes** [takeflight/wagtail-metadata#24]
Currently unless the user adds `itemscope itemtype="http://schema.org/WebPage"` to the `<html>` tag the metadata doesnt validate. In some cases (eg. Google) this means they will not use it.

Schema.org supports embedding a JSON-LD blob that includes the same metadata. If we switch to using that method we can output the `itemtype/itemscope` with the template tag. [Schema.org includes examples using JSON-LD](https://schema.org/WebPage#eg-12) so one can only assume it is actually supported. 

One thing to check is I'm not sure if that JSON-LD blob should appear in the `<head>` or at the end of the body - I've see both in the wild.

Further reading:
https://developers.google.com/schemas/formats/json-ld

**Comment by seb-b** [comment]
This was moved to another project https://github.com/takeflight/wagtail-schema.org
