### ISSUE TITLE
Extend metadata plugin to include options for Organisation

### ISSUE THREAD

**Issue by jonnyscholes** [takeflight/wagtail-metadata#26]
It would be great if in the global settings we could have a number of fields that are used to generate organisation metadata about the website.

An example of what I think should be our standard list of supported attributes - these come from Googles suggested (and in most instances required) attributes. Marked up assuming #24 is implemented:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.your-company-site.com",
  "logo": "http://www.example.com/images/logo.png",
  "name": "Company Name",
  "description": "Brief company description",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Paris, France",
    "postalCode": "F-75002",
    "streetAddress": "38 avenue de l'Opera"
  },
  "telephone": "+1-401-555-1212",
  "email": "secretariat(at)google.org",
  "sameAs": [
    "http://www.facebook.com/your-profile",
    "http://instagram.com/yourProfile",
    "http://www.linkedin.com/in/yourprofile",
    "http://plus.google.com/your_profile"
  ],
  "contactPoint": [{
    "@type": "ContactPoint",
    "telephone": "+1-401-555-1212",
    "contactType": "customer service"
  }]
}
</script>
```

_Notes for implementation:_

`sameAs` is a list of social profiles that are used by the same entity as the website. Supported social networks networks include:
- Facebook
- Twitter
- Google+
- Instagram
- YouTube
- LinkedIn
- Myspace
- Pinterest
- SoundCloud
- Tumblr

`telephone` should be used if the entity only has a sinlge phone number. `contactPoint`s should be used if they have multiple eg `customer service`, `sales`, `support`, `reception` etc. `contactType` is just a textfield - there is no white list - but perhaps we should provide a list of options? Otherwise people might add nonsensical data.

List of `contactType`s currently supported by Google:

```
"customer support", "technical support", "billing support", "bill payment", "sales", "reservations", "credit card support", "emergency", "baggage tracking", "roadside assistance", "package tracking"
```

Further reading:
https://schema.org/Organization
https://developers.google.com/search/docs/data-types/corporate-contacts
https://search.google.com/structured-data/testing-tool/

**Comment by timheap** [comment]
Suggested implementation below.

In `wagtailmetadata.models`:
```python
class JsonLDBase(BaseSetting):
    type = None

    logo = models.ForeignKey(
        get_image_model_string(), null=True, blank=True,
        related_name='+', on_delete=models.SET_NULL)
    description = models.TextField()

    def get_name(self):
        raise NotImplementedError

    def get_url(self):
        return self.site.root_url

    def to_json_ld(self):
        return {
            '@context': 'http://schema.org',
            '@type': self.type,
            'url': self.get_url(),
            'name': self.get_name(),
            'logo': resize_image(self.logo, 'max-256x256'),
            'description': self.description,
        }


class PersonLD(JsonLDBase):
    type = 'Person'
    name = models.CharField(max_length=255, help_text='Your name')

    def get_name(self):
        return self.name


class OrganisationLD(JsonLDBase):
    type = 'Organisation'

    def get_name(self):
        return self.site.site_name
```

In your webiste:
```python
@register_setting
@register_json_ld
class DigitalReadyLD(OrganisationLD):
   email = models.EmailField()

   def to_json_ld(self):
       json = super().to_json_ld()
       social_media = SocialMediaAccounts.for_site(self.site)
       json.update({
           'email': self.email,
           'sameAs': list(filter(bool, [
               social_media.facebook_url,
               social_media.twitter_url,
               social_media.linkedin_url,
           ]))
       })
       return json
```

This plugin can be opinionated, but we should think carefully about making any of these fields required. Making a required field not required for a single site is annoying.

**Comment by SalahAdDin** [comment]
Are metadata supported by wagtail rest api?

**Comment by seb-b** [comment]
This was moved to another project https://github.com/takeflight/wagtail-schema.org

**Comment by SalahAdDin** [comment]
@seb-b What's about use both packages in the same Pages?

**Comment by seb-b** [comment]
yep, that's possible. We use both for sites that require it
