### ISSUE TITLE
Unknown field(s) (search_image) specified for HomePage

### ISSUE THREAD

**Issue by Nielssie** [takeflight/wagtail-metadata#31]
Have some problem instaling wagtail-metadata. So I started with a fresh Wagtail.

I get this error while I try to start up Django/ wagtail.
Made a clean setup which gives me this error:

Unknown field(s) (search_image) specified for HomePage

models.py:

from wagtail.wagtailcore.models import Page
from wagtailmetadata.models import MetadataPageMixin

class HomePage(MetadataPageMixin,Page):
    pass

I am using 
beautifulsoup4==4.5.1
Django==1.10.2
django-modelcluster==2.0
django-taggit==0.18.3
django-treebeard==4.0.1
djangorestframework==3.4.7
html5lib==0.999999
Pillow==3.4.2
pytz==2016.7
six==1.10.0
Unidecode==0.4.19
wagtail==1.6.3
wagtail-metadata==0.3.0
Willow==0.3.1

**Comment by timheap** [comment]
Are you running on Python 2? If so, this might be related to [Django ticket #27337](https://code.djangoproject.com/ticket/27337). If you are running on Python 2, you can fix this in two ways: Upgrade to Python 3, or add a Metaclass that for some reason fixes things - see [the tests for an example](https://github.com/takeflight/wagtail-metadata/blob/master/tests/app/models.py#L8-L14)

**Comment by Nielssie** [comment]
thx, that is a work around
