### ISSUE TITLE
Previews not working correctly with the metadata tags - AttributeError: 'WSGIRequest' object has no attribute 'site'

### ISSUE THREAD

**Issue by bmoe872** [takeflight/wagtail-metadata#36]
# Relevant Setup Info
Jinja2==2.9.5
Python==3.5.2
Wagtail==1.11.1
wagtail-metadata==0.3.1

I have the template tags in my jinja2 extensions per the installation instructions

# Error I am getting
`AttributeError: 'WSGIRequest' object has no attribute 'site'`

Stack trace says its happening here:
```
def meta_tags(request, model):
    context = {
        'site_name': request.site.site_name,
        'object': model,
    }
```

# Steps to reproduce
1. Make a new page in wagtail that has a Jinja2 template with the wagtailmetadata tags
2. Click preview
3. Breaks.

**Comment by bmoe872** [comment]
A little update here - I added the `WAGTAIL_AUTO_UPDATE_PREVIEW = True` flag in settings.py, and somehow that seems to have fixed it.

**Comment by SableWalnut** [comment]
@bmoe872 Did you have `wagtail.wagtailcore.middleware.SiteMiddleware` in your `MIDDLEWARE_CLASSES` setting?

**Comment by bmoe872** [comment]
@SableWalnut Yes I did/do. We still use this today, and its working fine for now.
