### ISSUE TITLE
Pull the metadata settings into contrib module

### ISSUE THREAD

**Issue by seb-b** [takeflight/wagtail-metadata#39]
To keep this plugin lightweight the MetadataSettings model should be pulled out to a separate module so it's not mandatory. Users can then choose if they would like to include it or not.

**Comment by timheap** [comment]
Thinking about this more, I am not sure that pulling it out in to a contrib module is even the right approach. I think a better approach is dropping the model completely, and then writing a guide on how to add extra information to your site. Each site will need some extra information and not others. Not all sites have a twitter handle, or a Facebook app ID, but then some sites have [actual phone apps they may want to include in their twitter card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/app-card.html), which this plugin is not going to support. Showing people how to make the right extensions to suit them is much more future proof.
